[2024-11-18T23:51:07.458+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_broker_postgres.extract manual__2024-11-18T23:50:59.899433+00:00 [queued]>
[2024-11-18T23:51:07.505+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_broker_postgres.extract manual__2024-11-18T23:50:59.899433+00:00 [queued]>
[2024-11-18T23:51:07.507+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-18T23:51:07.555+0000] {taskinstance.py:2217} INFO - Executing <Task(RabbitMQSensor): extract> on 2024-11-18 23:50:59.899433+00:00
[2024-11-18T23:51:07.567+0000] {standard_task_runner.py:60} INFO - Started process 361 to run task
[2024-11-18T23:51:07.574+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'python_broker_postgres', 'extract', 'manual__2024-11-18T23:50:59.899433+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/python_broker_postgres.py', '--cfg-path', '/tmp/tmpqddbt28f']
[2024-11-18T23:51:07.579+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask extract
[2024-11-18T23:51:07.781+0000] {task_command.py:423} INFO - Running <TaskInstance: python_broker_postgres.extract manual__2024-11-18T23:50:59.899433+00:00 [running]> on host e8cb2db159e8
[2024-11-18T23:51:07.996+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='python_broker_postgres' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T23:50:59.899433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T23:50:59.899433+00:00'
[2024-11-18T23:51:08.026+0000] {base.py:83} INFO - Using connection ID 'RabbitMQ' for task execution.
[2024-11-18T23:51:08.038+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.6', 5672)
[2024-11-18T23:51:08.047+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=93, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.5', 42042), raddr=('172.18.0.6', 5672)>
[2024-11-18T23:51:08.055+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e28c7f0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e28c7f0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>).
[2024-11-18T23:51:08.087+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e28c7f0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:51:08.090+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e28c7f0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:51:08.091+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e28c7f0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:51:08.093+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2024-11-18T23:51:08.121+0000] {channel.py:536} INFO - Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e28c7f0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>>
[2024-11-18T23:51:08.127+0000] {channel.py:1133} INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e28c7f0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>>
[2024-11-18T23:52:08.194+0000] {base.py:83} INFO - Using connection ID 'RabbitMQ' for task execution.
[2024-11-18T23:52:08.200+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.6', 5672)
[2024-11-18T23:52:08.202+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=97, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.5', 40738), raddr=('172.18.0.6', 5672)>
[2024-11-18T23:52:08.204+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2b24c0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2b24c0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>).
[2024-11-18T23:52:08.220+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2b24c0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:52:08.221+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2b24c0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:52:08.223+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2b24c0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:52:08.225+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2024-11-18T23:52:08.230+0000] {channel.py:536} INFO - Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2b24c0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>>
[2024-11-18T23:52:08.233+0000] {channel.py:1133} INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2b24c0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>>
[2024-11-18T23:53:08.299+0000] {base.py:83} INFO - Using connection ID 'RabbitMQ' for task execution.
[2024-11-18T23:53:08.304+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.6', 5672)
[2024-11-18T23:53:08.306+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=101, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.5', 50116), raddr=('172.18.0.6', 5672)>
[2024-11-18T23:53:08.308+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2493d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2493d0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>).
[2024-11-18T23:53:08.318+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2493d0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:53:08.320+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2493d0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:53:08.321+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2493d0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:53:08.323+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2024-11-18T23:53:08.332+0000] {channel.py:536} INFO - Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2493d0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>>
[2024-11-18T23:53:08.335+0000] {channel.py:1133} INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e2493d0> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>>
[2024-11-18T23:53:41.534+0000] {job.py:213} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 308, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-18T23:53:41.862+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T23:54:08.361+0000] {base.py:83} INFO - Using connection ID 'RabbitMQ' for task execution.
[2024-11-18T23:54:08.366+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.18.0.6', 5672)
[2024-11-18T23:54:08.368+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=105, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.5', 35220), raddr=('172.18.0.6', 5672)>
[2024-11-18T23:54:08.371+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e249970>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e249970> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>).
[2024-11-18T23:54:08.384+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e249970> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:54:08.386+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e249970> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:54:08.387+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e249970> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>
[2024-11-18T23:54:08.389+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2024-11-18T23:54:08.395+0000] {channel.py:536} INFO - Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e249970> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>>
[2024-11-18T23:54:08.398+0000] {channel.py:1133} INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f225e249970> params=<ConnectionParameters host=rabbitmq_main port=5672 virtual_host=/ ssl=False>>>
[2024-11-18T23:54:08.403+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-11-18T23:54:08.539+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=python_broker_postgres, task_id=extract, execution_date=20241118T235059, start_date=20241118T235107, end_date=20241118T235408
[2024-11-18T23:54:08.635+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-18T23:54:08.736+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
